# Generated by Django 3.0.4 on 2020-04-01 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_collection', '0005_auto_20200401_0259'),
        ('dashboards', '0003_auto_20200401_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='the_collection.Book'),
        ),
    ]
