# Generated by Django 3.0.4 on 2020-04-01 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_collection', '0005_auto_20200401_0259'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0004_auto_20200401_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='the_collection.Book'),
        ),
        migrations.RemoveField(
            model_name='borrowed',
            name='borrowed_by',
        ),
        migrations.AddField(
            model_name='borrowed',
            name='borrowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
