# Generated by Django 3.0.4 on 2020-04-02 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_collection', '0006_auto_20200401_1443'),
        ('dashboards', '0006_auto_20200401_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiting',
            name='book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='the_collection.Book'),
        ),
    ]
