# Generated by Django 3.0.4 on 2020-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(blank=True, max_length=500, null=True)),
                ('ISBN', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_pages', models.IntegerField()),
                ('book_format', models.CharField(choices=[(1, 'Hardcover'), (2, 'Paperback'), (3, 'Audio-book'), (4, 'E-book'), (5, 'Newspaper'), (6, 'Magazine'), (7, 'Journal')], default=1, max_length=20)),
                ('book_status', models.CharField(choices=[(1, 'Available'), (2, 'Reserved'), (3, 'Borrowed')], default=1, max_length=20)),
                ('copies_available', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
