# Generated by Django 3.0.4 on 2020-03-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_collection', '0002_auto_20200324_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.IntegerField(choices=[(1, 'Hardcover'), (2, 'Paperback'), (3, 'Audio-book'), (4, 'E-book'), (5, 'Newspaper'), (6, 'Magazine'), (7, 'Journal')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Reserved'), (3, 'Borrowed')], default=1, max_length=20),
        ),
    ]
