# Generated by Django 3.0.4 on 2020-03-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_collection', '0004_auto_20200324_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Borrowed')], default=1),
        ),
    ]
